spring:  
  application:
    name: order-service
  kafka:
    bootstrap-servers: 192.168.99.100:9092
  cloud:  
    stream:
      bindings:
        output:
          destination: orders-out
          producer:
            partitionKeyExpression: payload.customerId
            partitionCount: 2
        input:
          destination: orders-in
      kafka:
        binder:
          zkNodes: 192.168.99.100
          
server:  
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true