spring:  
  application:
    name: account-service
  kafka:
    bootstrap-servers: 192.168.99.100:9092
  cloud:  
    stream:
      bindings:
        output:
          destination: orders-in
        input:
          consumer:
            partitioned: true
          destination: orders-out
          group: account
      kafka:
        binder:
          zkNodes: 192.168.99.100
          
server:  
  port: ${PORT:8091}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  profiles: instance1
  cloud:
    stream:
      instanceCount: 2
      instanceIndex: 0
server:  
  port: ${PORT:8091}  

---
spring:
  profiles: instance2
  cloud:
    stream:
      instanceCount: 2
      instanceIndex: 1
server:  
  port: ${PORT:9091} 